version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">=13.x"
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - ">=13"
  - dependency-name: node
    versions:
    - 12.20.1.pre.alpine
    - 12.20.2.pre.alpine
    - 12.21.0.pre.alpine
    - 12.22.0.pre.alpine
- package-ecosystem: npm
  directory: "/black-box-tests/acceptance-tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">=13.x"
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.12.7
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
- package-ecosystem: docker
  directory: "/black-box-tests/acceptance-tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - ">=13"
  - dependency-name: cypress/included
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
- package-ecosystem: npm
  directory: "/black-box-tests/accessibility-tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">=13.x"
- package-ecosystem: docker
  directory: "/black-box-tests/accessibility-tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - ">=13"
  - dependency-name: node
    versions:
    - 12.20.1.pre.alpine
    - 12.20.2.pre.alpine
    - 12.21.0.pre.alpine
    - 12.22.0.pre.alpine
